### ISSUE TITLE
Alternative usage with 'native' `beforeEach`

### ISSUE THREAD

**Issue by Q-back** [piotrszyma/teststate#1]
I often catch myself feeling like using `testState` throws me out of the `jest` testing flow. Normally I would put everything into the `beforeEach` hook, but I must use `testState` - specific syntax to have the state available inside my tests. It brings always few questions to my head:
* Should I place in `teststate(() => ..., beforeEach)` all the code that I'd normally place inside `beforeEach`?
* Or maybe I should have separate `teststate` and `beforeEach`?

So I'd like to have the possibility to write code like this:

```javascript
import { resetState } from "teststate";

describe("My tests", () => {
  const state = {
    myKey: "myValue",
  };
  beforeEach(() => {
    resetState(state);
  });
  
  it("tests something", () => {
    expect(state.myKey).toEqual("myValue");
  })
});
```

WDYT?

**Comment by piotrszyma** [comment]
I like your idea - code looks much simpler. Check #5  - it is a little bit tricky but seems to work as expected!

**Comment by piotrszyma** [comment]
A new, slightly modified implementation, was added in #5.
